services:
  smartlock.api:
    image: ${DOCKER_REGISTRY-}smartlockapi
    container_name: smartlock.api
    build:
      context: .
      dockerfile: src/SmartLock.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081

  smartlock.postgres:
    image: postgres:latest
    container_name: smartlock.postgres
    volumes:
      - ./.containers/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: smartlock
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  smartlock.keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: smartlock.keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://smartlock.keycloak-postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on:
      - smartlock.keycloak-postgres
    ports:
      - 8080:8080

  smartlock.keycloak-postgres:
    image: postgres:latest
    container_name: smartlock.keycloak-postgres
    volumes:
      - ./.containers/keycloak-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5433